### ISSUE TITLE
Mensagem de sem "conexão", quando a combobox sexo é preenchido

### ISSUE THREAD

**Issue by r-leafar** [andrebr45/Crud-Python-MySQL#1]
Como não é possível personaliza as informações do campo sexo, somente podendo escolher dentre masculino/feminino então deveria bloquear a combobox para edição. Quando você insere qualquer valor para algo diferente do permitido a interface desconecta com o banco de dados e fica aparecendo a mensagem de sem conexão, comportamento esse que aparente ser incorreto e deve ser tratado.

**Comment by andrebr45** [comment]
Estava ciente disto, estarei tentando resolver, muito obrigado!
